
#ifndef EMPTY_STACK_EXCEPTION_9W8HRG98HWE9GH8GW9ERH8G
#define EMPTY_STACK_EXCEPTION_9W8HRG98HWE9GH8GW9ERH8G

#include <exception>

class EmptyStackException : public std::exception{

};

#endif //EMPTY_STACK_EXCEPTION_9W8HRG98HWE9GH8GW9ERH8G
