
#ifndef EXCEEDS_STACK_SIZE_EXCEPTION_IQWUEIUWQEFIBWEFIB
#define EXCEEDS_STACK_SIZE_EXCEPTION_IQWUEIUWQEFIBWEFIB

#include <exception>

class ExceedsStackSizeException : public std::exception{

};

#endif //EXCEEDS_STACK_SIZE_EXCEPTION_IQWUEIUWQEFIBWEFIB
